CREATE TABLE IF NOT EXISTS invoices (
  id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
  invoice_number VARCHAR(48) NOT NULL UNIQUE,
  invoice_type ENUM('customer', 'staff_payout') NOT NULL,
  status ENUM('issued', 'paid') NOT NULL,
  booking_id CHAR(36) NULL UNIQUE,
  payout_request_id CHAR(36) NULL UNIQUE,
  recipient_name VARCHAR(200) NOT NULL,
  recipient_email VARCHAR(320) NULL,
  recipient_phone VARCHAR(80) NULL,
  recipient_detail TEXT NULL,
  payment_method TEXT NULL,
  currency CHAR(3) NOT NULL DEFAULT 'USD',
  issued_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  due_date DATE NULL,
  subtotal_usd DECIMAL(12,2) NOT NULL,
  service_charge_usd DECIMAL(12,2) NOT NULL DEFAULT 0,
  tax_usd DECIMAL(12,2) NOT NULL DEFAULT 0,
  total_usd DECIMAL(12,2) NOT NULL,
  line_items JSON NOT NULL,
  source_snapshot JSON NOT NULL,
  notes TEXT NULL,
  issued_by CHAR(36) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  CONSTRAINT fk_invoices_booking FOREIGN KEY (booking_id) REFERENCES bookings(id) ON DELETE RESTRICT,
  CONSTRAINT fk_invoices_payout FOREIGN KEY (payout_request_id) REFERENCES payout_requests(id) ON DELETE RESTRICT,
  CONSTRAINT fk_invoices_issuer FOREIGN KEY (issued_by) REFERENCES users(id) ON DELETE RESTRICT,
  CHECK (
    (invoice_type = 'customer' AND status = 'issued' AND booking_id IS NOT NULL AND payout_request_id IS NULL)
    OR
    (invoice_type = 'staff_payout' AND status = 'paid' AND booking_id IS NULL AND payout_request_id IS NOT NULL)
  ),
  CHECK (currency = 'USD'),
  CHECK (due_date IS NULL OR due_date >= DATE(issued_at)),
  CHECK (subtotal_usd >= 0),
  CHECK (service_charge_usd >= 0),
  CHECK (tax_usd >= 0),
  CHECK (total_usd > 0),
  CHECK (total_usd = subtotal_usd + service_charge_usd + tax_usd),
  CHECK (JSON_TYPE(line_items) = 'ARRAY'),
  CHECK (JSON_TYPE(source_snapshot) = 'OBJECT'),
  INDEX idx_invoices_type_issued (invoice_type, issued_at),
  INDEX idx_invoices_recipient (recipient_name),
  INDEX idx_invoices_issued_by (issued_by, issued_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
