CREATE TABLE IF NOT EXISTS package_types (
  id CHAR(36) PRIMARY KEY DEFAULT (UUID()),
  name VARCHAR(80) NOT NULL,
  slug VARCHAR(80) NOT NULL UNIQUE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  CHECK (CHAR_LENGTH(TRIM(name)) BETWEEN 1 AND 80),
  CHECK (CHAR_LENGTH(TRIM(slug)) BETWEEN 1 AND 80)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT IGNORE INTO package_types (id, name, slug) VALUES
  (UUID(), 'Regular', 'regular'),
  (UUID(), 'Private', 'private'),
  (UUID(), 'Kids', 'kids');

ALTER TABLE packages
  MODIFY COLUMN package_type VARCHAR(80) NOT NULL;
