'use client';

import Link from 'next/link';
import { useEffect, useState } from 'react';

const EMPTY_EVENT = { title: '', eventType: 'resort', startsAt: '', endsAt: '', description: '', sourceName: 'Resort', sourceUrl: '', visibility: 'both', isPublished: true };
const DEFAULT_LOCATION = { name: 'Jakarta, Indonesia', latitude: -6.2088, longitude: 106.8456, timezone: 'Asia/Jakarta' };
const formatDate = (value) => new Intl.DateTimeFormat('id-ID', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value));

export default function SkyEventsAdminPage() {
  const [events, setEvents] = useState([]); const [eventForm, setEventForm] = useState(EMPTY_EVENT); const [location, setLocation] = useState(DEFAULT_LOCATION); const [message, setMessage] = useState('');
  const load = async () => { const [eventResponse, settingsResponse] = await Promise.all([fetch('/api/sky-events?scope=admin&from=2020-01-01&to=2035-12-31'), fetch('/api/sky-settings')]); const eventData = await eventResponse.json(); const settingsData = await settingsResponse.json(); if (eventResponse.ok) setEvents(eventData.events || []); else setMessage(eventData.error || 'Gagal memuat event.'); if (settingsData.location) setLocation(settingsData.location); };
  useEffect(() => { const timer = setTimeout(() => { load(); }, 0); return () => clearTimeout(timer); }, []);
  const createEvent = async (event) => { event.preventDefault(); const response = await fetch('/api/sky-events', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(eventForm) }); const data = await response.json(); if (!response.ok) return setMessage(data.error || 'Event gagal dibuat.'); setEventForm(EMPTY_EVENT); setMessage('Event berhasil dibuat.'); await load(); };
  const togglePublished = async (item) => { const response = await fetch(`/api/sky-events/${item.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ isPublished: !item.isPublished }) }); if (!response.ok) return setMessage('Status event gagal diperbarui.'); await load(); };
  const removeEvent = async (item) => { if (!window.confirm(`Hapus event ${item.title}?`)) return; const response = await fetch(`/api/sky-events/${item.id}`, { method: 'DELETE' }); if (!response.ok) return setMessage('Event gagal dihapus.'); await load(); };
  const saveLocation = async (event) => { event.preventDefault(); const response = await fetch('/api/sky-settings', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(location) }); const data = await response.json(); if (!response.ok) return setMessage(data.error || 'Lokasi gagal disimpan.'); setLocation(data.location); setMessage('Lokasi pilot disimpan.'); };
  return <div className="fade-in-up">
    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 12, flexWrap: 'wrap', marginBottom: 20 }}><div><div style={{ fontSize: 11, letterSpacing: '0.12em', color: 'var(--text-dim)' }}>SKY GUIDE / PWA</div><h1 style={{ margin: '4px 0 0', fontSize: 27 }}>Kalender Langit</h1></div><Link href="/sky" target="_blank" className="btn btn-secondary">Buka Sky Guide</Link></div>
    <div className="card" style={{ marginBottom: 22 }}><div className="card-header"><span className="card-title">Lokasi Pilot Indonesia</span></div><form className="card-body" onSubmit={saveLocation}><div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, minmax(0, 1fr))', gap: 14 }}><Field label="Nama lokasi" value={location.name} onChange={(name) => setLocation({ ...location, name })} required /><Field label="Latitude" type="number" step="any" value={location.latitude} onChange={(latitude) => setLocation({ ...location, latitude })} required /><Field label="Longitude" type="number" step="any" value={location.longitude} onChange={(longitude) => setLocation({ ...location, longitude })} required /><Field label="Zona waktu IANA" value={location.timezone} onChange={(timezone) => setLocation({ ...location, timezone })} required /></div><div style={{ marginTop: 16 }}><button className="btn btn-primary" type="submit">Simpan Lokasi</button></div></form></div>
    <div className="card" style={{ marginBottom: 22 }}><div className="card-header"><span className="card-title">Tambah Event Resort atau Meteor</span></div><form className="card-body" onSubmit={createEvent}><div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, minmax(0, 1fr))', gap: 14 }}><Field label="Judul" value={eventForm.title} onChange={(title) => setEventForm({ ...eventForm, title })} required /><Select label="Jenis" value={eventForm.eventType} options={['resort', 'meteor', 'astronomy']} onChange={(eventType) => setEventForm({ ...eventForm, eventType })} /><Select label="Arah panduan" value={eventForm.visibility} options={['both', 'north', 'south']} onChange={(visibility) => setEventForm({ ...eventForm, visibility })} /><Field label="Mulai" type="datetime-local" value={eventForm.startsAt} onChange={(startsAt) => setEventForm({ ...eventForm, startsAt })} required /><Field label="Selesai" type="datetime-local" value={eventForm.endsAt} onChange={(endsAt) => setEventForm({ ...eventForm, endsAt })} /><Field label="Sumber" value={eventForm.sourceName} onChange={(sourceName) => setEventForm({ ...eventForm, sourceName })} /></div><label className="input-group" style={{ marginTop: 14 }}><span className="input-label">Deskripsi</span><textarea className="input" rows="3" value={eventForm.description} onChange={(event) => setEventForm({ ...eventForm, description: event.target.value })} /></label><div style={{ marginTop: 16, display: 'flex', gap: 12, alignItems: 'center', flexWrap: 'wrap' }}><label style={{ fontSize: 13, display: 'flex', gap: 8, alignItems: 'center' }}><input type="checkbox" checked={eventForm.isPublished} onChange={(event) => setEventForm({ ...eventForm, isPublished: event.target.checked })} /> Tampilkan ke tamu</label><button className="btn btn-primary" type="submit">Tambah Event</button>{message && <span style={{ color: 'var(--text-muted)', fontSize: 12 }}>{message}</span>}</div></form></div>
    <div className="card"><div className="card-header"><span className="card-title">Event yang Dikelola</span></div><div className="table-container"><table><thead><tr><th>Event</th><th>Waktu</th><th>Jenis</th><th>Arah</th><th>Status</th><th style={{ textAlign: 'right' }}>Aksi</th></tr></thead><tbody>{events.length ? events.map((item) => <tr key={item.id}><td><strong>{item.title}</strong><div style={{ color: 'var(--text-dim)', fontSize: 11 }}>{item.sourceName || 'Tanpa sumber'}</div></td><td>{formatDate(item.startsAt)}</td><td>{item.eventType}</td><td>{item.visibility}</td><td><span className={`tag ${item.isPublished ? 'tag-completed' : 'tag-cancelled'}`}>{item.isPublished ? 'Publik' : 'Draft'}</span></td><td style={{ textAlign: 'right', whiteSpace: 'nowrap' }}><button className="btn btn-secondary btn-sm" onClick={() => togglePublished(item)}>{item.isPublished ? 'Sembunyikan' : 'Publikasikan'}</button> <button className="btn btn-ghost btn-sm" onClick={() => removeEvent(item)}>Hapus</button></td></tr>) : <tr><td colSpan="6" style={{ textAlign: 'center', color: 'var(--text-dim)' }}>Belum ada event yang dikelola.</td></tr>}</tbody></table></div></div>
  </div>;
}
function Field({ label, type = 'text', value, onChange, required, step }) { return <label className="input-group"><span className="input-label">{label}</span><input className="input" type={type} step={step} value={value} onChange={(event) => onChange(event.target.value)} required={required} /></label>; }
function Select({ label, value, options, onChange }) { return <label className="input-group"><span className="input-label">{label}</span><select className="input" value={value} onChange={(event) => onChange(event.target.value)}>{options.map((option) => <option key={option} value={option}>{option}</option>)}</select></label>; }
