'use client';

import { createContext, useContext, useEffect, useState, useCallback } from 'react';

export const translations = {
  id: {
    // Navigation & Sidebar
    nav_dashboard: 'Dasbor',
    nav_bookings: 'Daftar Booking',
    nav_booking_form: 'Form Booking',
    nav_package: 'Paket Observasi',
    nav_payout: 'Pencairan Komisi',
    nav_calendar: 'Kalender Jadwal',
    nav_settings: 'Pengaturan',
    nav_main_section: 'Navigasi Utama',
    nav_active_locations: 'Lokasi Aktif',
    nav_logout: 'Keluar Akun',

    // Role Labels
    role_internal: 'Staff Internal',
    role_external: 'Staff External',
    role_astronomer: 'Astronom In-House',
    resort_profile: 'Profil Resort',

    // Header & Clock
    clock_wib: 'WIB',
    clock_utc: 'UTC',
    clock_date: 'Tanggal',
    btn_new_booking: '+ Booking Baru',

    // Settings Page
    settings_title: 'Pengaturan',
    settings_subtitle: 'Kelola preferensi akun, bahasa antarmuka, dan notifikasi Anda.',
    settings_profile_title: 'Profil Pengguna',
    settings_name: 'Nama Lengkap',
    settings_institution: 'Institusi / Peran',
    settings_language_title: 'Bahasa Aplikasi (Language)',
    settings_language_desc: 'Pilih bahasa tampilan antarmuka aplikasi staf (Indonesia atau English).',
    settings_lang_id: 'Bahasa Indonesia (ID)',
    settings_lang_en: 'English (EN)',
    settings_notif_title: 'Notifikasi',
    settings_notif_email_label: 'Notifikasi Email',
    settings_notif_email_desc: 'Terima pemberitahuan status booking melalui email.',
    settings_saved_toast: 'Pengaturan bahasa berhasil diubah!',

    // Common Actions & Tags
    btn_save: 'Simpan',
    btn_cancel: 'Batal',
    btn_close: 'Tutup',
    btn_edit: 'Edit Booking',
    btn_delete: 'Hapus',
    btn_copy_notes: '📄 Salin Seluruh Catatan',
    btn_copied_success: '✓ Berhasil Disalin!',
    btn_open_notes: '🔍 Buka Catatan Lengkap (Popup)',
    btn_submit_booking: 'Submit Booking Observasi',
    btn_add_child: '+ Tambah Data Anak',
    btn_remove: 'Hapus',

    // Status Badges & Review
    status_pending_review: 'Pending',
    status_accepted: 'Aktif',
    status_rejected: 'Ditolak',
    status_booked: 'Booked',
    status_finished: 'Selesai',
    status_cancelled: 'Dibatalkan',
    tag_signed: '✓ Signed',
    tag_not_signed: '⏱ Not Signed',
    btn_accept_booking: 'Terima',
    btn_reject_booking: 'Tolak',
    btn_confirm_accept: 'Setujui booking ini?',
    btn_confirm_reject: 'Tolak booking ini?',
    confirm_accept_title: 'Konfirmasi Persetujuan Booking',
    confirm_reject_title: 'Konfirmasi Penolakan Booking',
    confirm_accept_desc: 'Booking ini akan disetujui (Accepted) dan otomatis masuk ke jadwal operasional & kalender staf internal.',
    confirm_reject_desc: 'Booking ini akan ditolak (Rejected) dan staf external pembuat booking akan menerima notifikasi status.',
    btn_yes_accept: '✓ Ya, Setujui Booking',
    btn_yes_reject: '✕ Ya, Tolak Booking',
    btn_cancel_action: 'Batal',
    modal_booking_details: 'Detail Reservasi',
    notifications: 'Notifikasi',
    loading_notifications: 'Mengambil data notifikasi...',
    no_notifications: 'Belum ada notifikasi baru.',
    open_notifications: 'Buka notifikasi',
    notification_new_count: '{count} baru',
    mark_all_read: 'Tandai Semua Dibaca',
    filter_all: 'Semua Booking',
    filter_pending_review: 'Pending',
    filter_internal: 'Booking Internal',
    filter_external: 'Booking External',
    search_booking_placeholder: 'Cari kode booking, nama package, tamu, kamar...',
    clear_search: 'Reset',

    // Booking View Modal
    view_title: 'Detail Reservasi Staf Operasional',
    view_stat_date: 'Tanggal Observasi',
    view_stat_time: 'Jam & Sesi',
    view_stat_room: 'Nomor Kamar / Villa',
    view_stat_nationality: 'Kebangsaan / Bahasa',
    view_stat_whatsapp: 'WhatsApp Tamu',
    view_stat_pax: 'Jumlah Tamu',
    view_stat_payment: 'Metode Pembayaran',
    view_stat_commission: 'Estimasi Komisi Staf',
    view_stat_star_reward: 'Reward Bintang',
    view_package_banner_title: 'Package Observasi Terpilih',
    view_guest_lead_title: 'Tamu Utama (Lead Guest)',
    view_guest_companion_title: 'Tamu 2 (Pasangan/Pendamping)',
    view_guest_child_title: 'Data Anak',
    view_guest_no_child: 'Tidak membawa anak (Couple / Dewasa saja)',
    view_package_label: 'Package',
    view_notes_banner_title: 'Rincian Catatan Lengkap & Log Form',
    view_notes_banner_desc: 'Klik tombol di kanan untuk membuka popup tampilan teks catatan lengkap di depan layar.',
    view_notes_popup_title: 'Catatan Lengkap & Log Intake Form',
    view_staff_notes_title: 'Catatan Khusus Operasional Lapangan',

    // Booking Form Sections & Fields
    form_title: 'Formulir Reservasi Observasi Tamu',
    form_desc: 'Isi data reservasi tamu untuk pengalaman pengamatan benda langit.',
    form_sec_guest_lead: '1. Data Tamu Utama (Kontak Reservasi)',
    form_sec_guest_companion: '2. Data Tamu 2 (Pasangan/Pendamping)',
    form_sec_children: '3. Data Anak (Opsional / Fleksibel)',
    form_sec_preferences: '4. Preferensi Pengalaman & Observasi',
    form_sec_notes: '5. Catatan Tambahan',
    form_label_name: 'Nama Lengkap Tamu',
    form_label_phone: 'Nomor WhatsApp',
    form_label_email: 'Email (Opsional)',
    form_label_room: 'Nomor Kamar / Villa',
    form_label_nationality: 'Kewarganegaraan',
    form_label_language: 'Bahasa Pilihan Tamu',
    form_label_adult_count: 'Jumlah Dewasa (Adults)',
    form_label_child_count: 'Jumlah Anak (Children)',
    form_label_date: 'Tanggal Observasi',
    form_label_time: 'Waktu / Jam Sesi',
    form_label_package: 'Pilih Package Utama',
    form_label_job: 'Pekerjaan (Opsional)',
    form_label_child_age: 'Umur Anak (Tahun)',
    form_label_child_gender: 'Jenis Kelamin',
    form_label_child_grade: 'Kelas / Jenjang Sekolah',
    form_label_child_interest: 'Tingkat Minat Astronomi',
    form_label_child_allergy: 'Alergi / Pantangan Makanan',
    form_label_child_comfort: 'Catatan Kenyamanan Anak',
    form_label_occasion: 'Momen / Acara Khusus',
    form_label_seating: 'Pengaturan Tempat Duduk',
    form_label_photo: 'Permintaan Foto Teleskop',
    form_label_privacy: 'Preferensi Privasi',
    form_label_reschedule: 'Persetujuan Cuaca / Reschedule',
    form_label_payment: 'Metode Pembayaran',
    form_placeholder_search: 'Cari tamu, paket, kamar...',
    form_pax_adult_only: 'Hanya Tamu Dewasa / Couple',
    form_pax_with_children: 'Tamu Membawa Anak',
    form_empty_children_prompt: 'Saat ini belum ada data anak ditambahkan (Cocok untuk Couple / Dewasa).',
    form_empty_children_btn: '+ Tambah Data Anak',
    form_alert_saved: 'Booking berhasil disimpan!',
    form_alert_error: 'Gagal menyimpan booking.',

    // Dashboard
    dashboard_internal_title: 'Dashboard Staff Internal',
    dashboard_external_title: 'Dashboard Observer Eksternal',
    dashboard_welcome: 'Selamat datang, {name}. Kelola booking customer resort di sini.',
    dashboard_total_bookings: 'Total Booking Saya',
    dashboard_active_bookings: 'Booking Aktif',
    dashboard_upcoming: 'Akan Datang',
    dashboard_finished: 'Selesai',
    dashboard_all_time: 'Sepanjang waktu',
    dashboard_operational_note: 'Langsung masuk operasional',
    dashboard_active_schedule: 'Jadwal booking aktif',
    dashboard_finished_note: 'Observasi selesai',
    dashboard_star_progress: 'Progress Bintang Staff',
    dashboard_points: '{points} / 50 poin',
    dashboard_star_rule: '10 booking = 1 bintang, package kids: 20 anak = 1 bintang',
    dashboard_history_title: 'Riwayat Booking (5 Teratas)',
    dashboard_see_all: 'Lihat Semua',
    dashboard_no_history: 'Tidak ada riwayat booking.',
    dashboard_booking_guide: 'Panduan Booking',
    dashboard_guide_new: 'Booking baru langsung tercatat di sistem operasional resort dengan status Menunggu.',
    dashboard_guide_status: 'Pantau status booking di tabel riwayat. Staff internal dapat memperbarui status sesuai proses operasional.',
    dashboard_guide_invoice: 'Pembayaran tetap dicatat manual oleh resort.',
    dashboard_guide_signed: 'Centang setelah tamu tanda tangan fisik.',
    dashboard_guide_feedback: 'Kirim link WhatsApp setelah experience selesai.',
    table_station: 'Stasiun',
    table_date: 'Tanggal',
    table_time: 'Waktu',

    // Calendar & Packages
    calendar_title: 'Kalender Booking Bulanan',
    calendar_all_staff: 'Kalender Semua Staff',
    calendar_resort: 'Kalender Booking Resort',
    calendar_month: 'Bulan',
    calendar_year: 'Tahun',
    calendar_this_month: 'booking bulan ini',
    calendar_selected_date: 'Tanggal Dipilih',
    calendar_loading: 'Memuat booking...',
    calendar_empty_title: 'Tidak ada booking',
    calendar_empty_desc: 'Tanggal ini masih kosong.',
    calendar_more: '+{count} lainnya',
    calendar_filter_label: 'Filter bulan dan tahun kalender',
    package_desc: 'Pilih service/package yang ingin dilihat atau digunakan untuk booking.',
    package_service_count: '{count} service',

    // Form UI Details
    btn_view: 'Lihat',
    btn_list: 'Lihat List',
    btn_check_availability: 'Cek Ketersediaan',
    btn_submit: 'Submit Booking',
    btn_update_booking: 'Update Booking',
    btn_saving: 'Menyimpan...',
    form_submitted_desc: 'Booking yang sudah dikirim ke admin untuk direview.',
    form_submitted_title: 'Daftar Booking',
    form_loading_bookings: 'Memuat booking...',
    form_no_bookings: 'Belum ada booking.',
    form_intake_title: 'Booking Intake Form',
    form_selected_package_empty: 'Pilih package untuk tamu',
    form_selected_package_desc: 'Data tamu utama, pasangan/pendamping, anak (opsional), dan pilihan package',
    form_adults: 'Dewasa',
    form_children: 'Anak',
    form_sec_reservation: 'Data Reservasi',
    form_sec_lead_compact: 'Data Tamu Utama (Kontak Reservasi)',
    form_sec_companion_compact: 'Data Tamu 2 (Pasangan / Pendamping)',
    form_sec_children_compact: 'Data Anak',
    form_sec_consent_notes: 'Consent & Catatan Tambahan',
    form_required: 'Wajib Diisi',
    form_optional: 'Opsional',
    form_label_full_name: 'Nama Lengkap',
    form_label_phone_short: 'WhatsApp / Telepon',
    form_label_occupation_company: 'Pekerjaan / Instansi',
    form_label_companion_job: 'Pekerjaan',
    form_label_lead_package: 'Package Tamu Utama',
    form_label_companion_package: 'Package Tamu 2',
    form_sec_extra_adult: 'Data Tamu {number}',
    form_label_extra_adult_package: 'Package Tamu {number}',
    form_label_child_package: 'Package Anak #{number}',
    form_child_added: '{count} Anak Ditambahkan',
    form_no_children: 'Tidak Membawa Anak',
    form_add_child: 'Tambah Anak',
    form_add_child_data: '+ Tambah Data Anak',
    form_no_child_data: 'Tidak ada data anak',
    form_no_child_desc: 'Jika tamu adalah pasangan (couple) atau tidak membawa anak, lewati bagian ini. Jika membawa anak, klik tombol di bawah.',
    form_child_tag: 'Anak #{number}',
    form_remove_child_title: 'Hapus anak ini',
    form_remove_child: 'Hapus',
    form_label_child_name: 'Nama Anak',
    form_label_child_age_years: 'Umur (Tahun)',
    form_label_school_grade: 'Kelas / Sekolah',
    form_label_astronomy_interest: 'Minat Astronomi',
    form_label_dietary: 'Alergi / Pantangan',
    form_label_child_notes: 'Catatan Khusus Anak',
    form_label_photo_consent: 'Photo Consent',
    form_label_weather_reschedule: 'Weather Reschedule',
    form_label_seating_setup: 'Seating / Setup',
    form_label_slot_status: 'Slot Status',
    form_label_occasion_compact: 'Occasion / Momen Khusus',
    form_label_extra_details: 'Detail Tambahan',
    form_label_internal_notes: 'Internal Notes',
    form_package_required_note: 'Pilih minimal satu package pada data tamu sebelum submit booking.',
    form_placeholder_room: 'Contoh: 205 / Villa 3',
    form_placeholder_lead_name: 'Nama tamu utama...',
    form_placeholder_optional: 'Opsional',
    form_placeholder_companion_name: 'Nama pasangan / pendamping...',
    form_placeholder_extra_adult_name: 'Nama tamu tambahan...',
    form_placeholder_same_as_lead: 'Opsional jika sama dengan tamu utama',
    form_placeholder_child_name: 'Nama lengkap anak...',
    form_placeholder_child_age: 'Contoh: 8',
    form_placeholder_grade: 'Contoh: Grade 3',
    form_placeholder_child_dietary: 'Alergi makanan/minuman atau none',
    form_placeholder_child_notes: 'Takut gelap, mudah bosan, perlu pendamping khusus, dll.',
    form_placeholder_occasion: 'Honeymoon, anniversary, birthday, family trip, dll.',
    form_placeholder_extra: 'Request khusus dari tamu...',
    form_placeholder_internal_notes: 'Catatan untuk admin/operasional internal...',
    form_option_male: 'Laki-laki (Male)',
    form_option_female: 'Perempuan (Female)',
    form_option_beginner: 'Pemula (Beginner)',
    form_option_curious: 'Sangat Tertarik (Curious)',
    form_option_advanced: 'Mahir untuk usianya',
    form_validation_date: 'Pilih tanggal terlebih dahulu.',
    form_validation_package: 'Pilih minimal satu package observasi untuk tamu.',
    form_validation_lead: 'Lengkapi Nama dan WhatsApp Tamu Utama terlebih dahulu.',
    form_validation_child: 'Lengkapi Nama dan Umur untuk Anak #{number}.',
    form_availability_ok: 'Slot ini tersedia dan booking akan langsung dicatat ke sistem operasional.',
    form_load_booking_error: 'Gagal memuat booking.',
    form_submit_error: 'Booking gagal dibuat.',
    form_submit_success_created: 'Booking {code} berhasil dibuat dan langsung tercatat di sistem operasional.',
    form_submit_success_updated: 'Booking {code} berhasil diperbarui di sistem operasional.',
    notes_code: 'Kode',
    notes_guest: 'Tamu',
    notes_empty: 'Tidak ada catatan tambahan yang terlampir.',
    common_first: 'Pertama',
    common_previous: 'Sebelumnya',
    common_today: 'Hari Ini',
    common_next: 'Berikutnya',
    common_last: 'Terakhir',
    common_date: 'Tanggal',
    common_status: 'Status',
    common_event: 'Event',
    common_pax: 'Pax',
    common_booking: 'Booking',
    common_guest: 'Tamu',
    common_package: 'Package',
    common_signed: 'Ditandatangani',
    common_commission: 'Komisi',
    common_action: 'Aksi',
    common_loading: 'Memuat...',
    common_yes: 'Ya',
    common_no: 'Tidak',
    common_room: 'Kamar',
    common_processing: 'Memproses...',
    common_showing: 'Menampilkan {start}-{end} dari {total}',
    booking_code: 'Kode Booking',
    booking_no_results: 'Belum ada booking',
    booking_by: 'Oleh {name}',
    dashboard_commission_total: 'Total Komisi Diperoleh',
    dashboard_status_label: 'Status',
    dashboard_invoice_label: 'Invoice',
    dashboard_signed_label: 'Tanda Tangan',
    dashboard_feedback_label: 'Feedback',
    dashboard_load_commission_error: 'Gagal memuat ringkasan komisi.',
    dashboard_load_reward_error: 'Gagal memuat ringkasan reward.',
    calendar_previous: 'Sebelumnya',
    calendar_today: 'Hari Ini',
    calendar_next: 'Berikutnya',
    package_title: 'Package',
    package_form_booking: 'Form Booking',
    package_service_title: 'Layanan Package',
    package_including: 'Termasuk',
    package_upon_request: 'Sesuai permintaan',
    payout_title: 'Ajukan Pencairan',
    payout_history: 'Riwayat Pencairan',
    payout_total_commission: 'Total Komisi Diperoleh',
    payout_total_commission_note: 'Booking selesai, ditandatangani, dan berbayar',
    payout_monthly_reward: 'Reward Bintang Bulan Ini',
    payout_processing: 'Dalam Proses / Selesai',
    payout_processing_note: 'Diajukan, diproses, dan selesai',
    payout_available: 'Bisa Dicairkan',
    payout_monthly_unit: '{count} unit bulan ini',
    payout_star_progress: 'Progress bintang bulanan',
    payout_next_star: 'Progress menuju bintang berikutnya',
    payout_amount: 'Jumlah USD',
    payout_bank: 'Bank',
    payout_account_holder: 'Nama Pemilik Rekening',
    payout_account_number: 'Nomor Rekening / Catatan',
    payout_notes: 'Catatan',
    payout_sending: 'Mengirim...',
    payout_request_count: '{count} permintaan',
    payout_admin_notes: 'Catatan Admin',
    payout_empty: 'Belum ada permintaan pencairan.',
    payout_load_error: 'Gagal memuat pencairan.',
    payout_request_error: 'Gagal mengirim permintaan pencairan.',
    payout_request_success: 'Permintaan pencairan terkirim ke admin.',
    payout_status_requested: 'Diajukan',
    payout_status_processed: 'Diproses',
    payout_status_completed: 'Selesai',
    payout_status_rejected: 'Ditolak',
    instruments_title: 'Instrumen',
    instruments_desc: 'Daftar teleskop yang tersedia di jaringan observatorium.',
    reports_title: 'Laporan',
    reports_desc: 'Laporan aktivitas booking dan observasi Anda.',
    reports_unavailable: 'Fitur Belum Tersedia',
    reports_unavailable_desc: 'Laporan untuk peran staff eksternal masih dalam pengembangan.',
    users_title: 'Pengguna',
    users_desc: 'Manajemen pengguna untuk staff eksternal.',
    users_unavailable: 'Fitur Belum Tersedia',
    users_unavailable_desc: 'Manajemen pengguna untuk peran staff eksternal masih dalam pengembangan.',
    reschedule_date: 'Tanggal baru (YYYY-MM-DD)',
    reschedule_start: 'Waktu mulai baru (HH:MM)',
    reschedule_end: 'Waktu selesai baru (HH:MM)',
    reschedule_reason: 'Alasan perubahan jadwal',
    reschedule_default_reason: 'Permintaan tamu',
    reschedule_failed: 'Gagal menjadwalkan ulang booking.',
    reschedule_success: 'Booking berhasil dijadwalkan ulang.',
    booking_complete: 'Selesaikan Booking',
    booking_cancel_guest: 'Batalkan oleh Tamu',
    booking_cancel_weather: 'Batalkan karena Cuaca',
    booking_reschedule: 'Jadwalkan Ulang',
    booking_guest: 'Tamu',
    booking_package: 'Package',
    booking_schedule: 'Jadwal',
    form_payment_room: 'Tagihan kamar',
    form_payment_cash: 'Tunai',
    form_payment_card: 'Kartu',
    form_payment_resort: 'Tagihan resort',
    form_photo_ask: 'Tanyakan tamu terlebih dahulu',
    form_photo_allowed: 'Diizinkan',
    form_photo_not_allowed: 'Tidak diizinkan',
    form_slot_available: 'Tersedia',
    form_slot_check: 'Perlu diperiksa',
    form_slot_confirmed: 'Dikonfirmasi',
    form_placeholder_nationality: 'Kebangsaan (contoh: Indonesia, Jepang)',
    form_placeholder_seating: 'Pasangan, keluarga berdekatan, pengaturan privat...',
    settings_resort_unset: 'Resort belum ditentukan',
    settings_interface_note: 'Hanya teks antarmuka aplikasi yang berubah. Data yang sudah dimasukkan pengguna tidak diubah.',
    settings_default_language: 'Default (ID)',
    settings_international_language: 'Internasional (EN)',
    api_error_invalid_booking: 'Data booking tidak valid.',
    api_error_invalid_payout: 'Data pencairan tidak valid.',
    api_error_staff_resort: 'Profil resort staf belum dikonfigurasi.',
    api_error_payout_balance: 'Jumlah melebihi saldo pencairan yang tersedia.',
    api_error_package_resort: 'Paket tidak ditemukan untuk resort ini.',
    api_error_package_missing: 'Paket tidak ditemukan.',
    api_error_staff_missing: 'Staf tidak ditemukan.',
    api_error_booking_missing: 'Booking tidak ditemukan.',
    api_error_invalid_booking_id: 'ID booking tidak valid.',
    api_error_invalid_reschedule: 'Data jadwal ulang tidak valid.',
    accessibility_toggle_menu: 'Buka atau tutup menu',
    accessibility_toggle_sidebar: 'Buka atau tutup sidebar',
    accessibility_close_menu: 'Tutup menu',
    accessibility_toggle_language: 'Ganti bahasa',
    experience_sun_observation_tagline: 'Sesi pengamatan matahari gratis pada siang hari.',
    experience_beach_stargazing_tagline: 'Pengamatan bintang malam dengan tempat duduk santai di Palm Beach.',
    experience_private_beach_stargazing_tagline: 'Sesi privat yang intim di Palm Beach.',
    experience_celestial_dining_tagline: 'Santap malam istimewa di bawah bintang-bintang di Palm Beach.',
    experience_kids_stargazing_tagline: 'Pengalaman mengamati bintang yang seru, edukatif, aman, dan ramah untuk anak.',
    experience_moon_observation_tagline: 'Pengamatan bulan terpandu yang disiarkan dari {location}.',
    experience_night_sky_tagline: 'Tur langit malam bidang luas yang disiarkan dari {location}.',
    experience_deep_sky_tagline: 'Pengamatan objek langit dalam yang disiarkan dari {location}.',
    dashboard_completed_count: '{count} booking selesai',
    dashboard_monthly_reward_amount: '{amount} bonus bulan ini',
    payout_star_breakdown: '{stars} bintang penuh + {amount} progres',
  },
  en: {
    // Navigation & Sidebar
    nav_dashboard: 'Dashboard',
    nav_bookings: 'Bookings',
    nav_booking_form: 'Booking Form',
    nav_package: 'Observation Packages',
    nav_payout: 'Commission Payout',
    nav_calendar: 'Schedule Calendar',
    nav_settings: 'Settings',
    nav_main_section: 'Main Navigation',
    nav_active_locations: 'Active Locations',
    nav_logout: 'Sign Out',

    // Role Labels
    role_internal: 'Internal Staff',
    role_external: 'External Staff',
    role_astronomer: 'In-House Astronomer',
    resort_profile: 'Resort Profile',

    // Header & Clock
    clock_wib: 'WIB',
    clock_utc: 'UTC',
    clock_date: 'Date',
    btn_new_booking: '+ New Booking',

    // Settings Page
    settings_title: 'Settings',
    settings_subtitle: 'Manage your profile, interface language, and notification preferences.',
    settings_profile_title: 'User Profile',
    settings_name: 'Full Name',
    settings_institution: 'Institution / Role',
    settings_language_title: 'Application Language',
    settings_language_desc: 'Select the interface language for the staff portal (Indonesian or English).',
    settings_lang_id: 'Bahasa Indonesia (ID)',
    settings_lang_en: 'English (EN)',
    settings_notif_title: 'Notifications',
    settings_notif_email_label: 'Email Notifications',
    settings_notif_email_desc: 'Receive booking status updates and review alerts via email.',
    settings_saved_toast: 'Language setting updated successfully!',

    // Common Actions & Tags
    btn_save: 'Save',
    btn_cancel: 'Cancel',
    btn_close: 'Close',
    btn_edit: 'Edit Booking',
    btn_delete: 'Delete',
    btn_copy_notes: '📄 Copy Entire Notes',
    btn_copied_success: '✓ Copied Successfully!',
    btn_open_notes: '🔍 Open Full Notes (Popup)',
    btn_submit_booking: 'Submit Observation Booking',
    btn_add_child: '+ Add Child Data',
    btn_remove: 'Remove',

    // Status Badges & Review
    status_pending_review: 'Pending',
    status_accepted: 'Active',
    status_rejected: 'Rejected',
    status_booked: 'Booked',
    status_finished: 'Finished',
    status_cancelled: 'Cancelled',
    tag_signed: '✓ Signed',
    tag_not_signed: '⏱ Not Signed',
    btn_accept_booking: 'Accept',
    btn_reject_booking: 'Reject',
    btn_confirm_accept: 'Approve this booking?',
    btn_confirm_reject: 'Reject this booking?',
    confirm_accept_title: 'Confirm Booking Approval',
    confirm_reject_title: 'Confirm Booking Rejection',
    confirm_accept_desc: 'This booking will be confirmed (Accepted) and added to active operational schedules.',
    confirm_reject_desc: 'This booking will be marked as rejected and the external staff will be notified.',
    btn_yes_accept: '✓ Yes, Approve Booking',
    btn_yes_reject: '✕ Yes, Reject Booking',
    btn_cancel_action: 'Cancel',
    modal_booking_details: 'Reservation Details',
    notifications: 'Notifications',
    loading_notifications: 'Loading notifications...',
    no_notifications: 'No new notifications.',
    open_notifications: 'Open notifications',
    notification_new_count: '{count} new',
    mark_all_read: 'Mark all as read',
    filter_all: 'All Bookings',
    filter_pending_review: 'Pending',
    filter_internal: 'Internal Bookings',
    filter_external: 'External Bookings',
    search_booking_placeholder: 'Search booking code, package name, guest, room...',
    clear_search: 'Reset',

    // Booking View Modal
    view_title: 'Operational Staff Reservation Detail',
    view_stat_date: 'Observation Date',
    view_stat_time: 'Time & Session',
    view_stat_room: 'Room / Villa Number',
    view_stat_nationality: 'Nationality / Language',
    view_stat_whatsapp: 'Guest WhatsApp',
    view_stat_pax: 'Guest Count',
    view_stat_payment: 'Payment Method',
    view_stat_commission: 'Est. Staff Commission',
    view_stat_star_reward: 'Star Reward',
    view_package_banner_title: 'Selected Observation Package',
    view_guest_lead_title: 'Lead Guest (Contact)',
    view_guest_companion_title: 'Guest 2 (Partner/Companion)',
    view_guest_child_title: 'Child Data',
    view_guest_no_child: 'No children (Couple / Adults only)',
    view_package_label: 'Package',
    view_notes_banner_title: 'Full Form Notes & Intake Log',
    view_notes_banner_desc: 'Click the button on the right to open the full raw notes popup on screen.',
    view_notes_popup_title: 'Full Form Notes & Intake Log',
    view_staff_notes_title: 'Field Operational Notes',

    // Booking Form Sections & Fields
    form_title: 'Guest Observation Booking Form',
    form_desc: 'Fill in guest reservation details for stargazing experience.',
    form_sec_guest_lead: '1. Lead Guest Data (Reservation Contact)',
    form_sec_guest_companion: '2. Guest 2 Data (Partner/Companion)',
    form_sec_children: '3. Children Data (Optional / Dynamic)',
    form_sec_preferences: '4. Observation Experience Preferences',
    form_sec_notes: '5. Additional Notes',
    form_label_name: 'Guest Full Name',
    form_label_phone: 'WhatsApp Number',
    form_label_email: 'Email (Optional)',
    form_label_room: 'Room / Villa Number',
    form_label_nationality: 'Nationality',
    form_label_language: 'Guest Preferred Language',
    form_label_adult_count: 'Adults Count',
    form_label_child_count: 'Children Count',
    form_label_date: 'Observation Date',
    form_label_time: 'Session Time',
    form_label_package: 'Select Main Package',
    form_label_job: 'Occupation (Optional)',
    form_label_child_age: 'Child Age (Years)',
    form_label_child_gender: 'Gender',
    form_label_child_grade: 'School Grade',
    form_label_child_interest: 'Astronomy Interest Level',
    form_label_child_allergy: 'Allergies / Dietary Restrictions',
    form_label_child_comfort: 'Child Comfort Notes',
    form_label_occasion: 'Special Occasion',
    form_label_seating: 'Seating Arrangement',
    form_label_photo: 'Telescope Photo Request',
    form_label_privacy: 'Privacy Preference',
    form_label_reschedule: 'Weather / Reschedule Consent',
    form_label_payment: 'Payment Method',
    form_placeholder_search: 'Search guest, package, room...',
    form_pax_adult_only: 'Adults Only / Couple',
    form_pax_with_children: 'Guests with Children',
    form_empty_children_prompt: 'No children added currently (Ideal for Couple / Adults).',
    form_empty_children_btn: '+ Add Child Data',
    form_alert_saved: 'Booking successfully saved!',
    form_alert_error: 'Failed to save booking.',

    // Dashboard
    dashboard_internal_title: 'Internal Staff Dashboard',
    dashboard_external_title: 'External Observer Dashboard',
    dashboard_welcome: 'Welcome, {name}. Manage resort customer bookings here.',
    dashboard_total_bookings: 'My Total Bookings',
    dashboard_active_bookings: 'Active Bookings',
    dashboard_upcoming: 'Upcoming',
    dashboard_finished: 'Completed',
    dashboard_all_time: 'All time',
    dashboard_operational_note: 'Sent directly to operations',
    dashboard_active_schedule: 'Active booking schedule',
    dashboard_finished_note: 'Completed observations',
    dashboard_star_progress: 'Staff Star Progress',
    dashboard_points: '{points} / 50 points',
    dashboard_star_rule: '10 bookings = 1 star, kids package: 20 children = 1 star',
    dashboard_history_title: 'Booking History (Top 5)',
    dashboard_see_all: 'See All',
    dashboard_no_history: 'No booking history.',
    dashboard_booking_guide: 'Booking Guide',
    dashboard_guide_new: 'New bookings are logged immediately in the resort operations system with Pending status.',
    dashboard_guide_status: 'Track bookings in the history table. Internal staff can update their status as operations progress.',
    dashboard_guide_invoice: 'Payments are still recorded manually by the resort.',
    dashboard_guide_signed: 'Check signed after the guest signs the physical form.',
    dashboard_guide_feedback: 'Send the WhatsApp feedback link after the experience is completed.',
    table_station: 'Station',
    table_date: 'Date',
    table_time: 'Time',

    // Calendar & Packages
    calendar_title: 'Monthly Booking Calendar',
    calendar_all_staff: 'All Staff Calendar',
    calendar_resort: 'Resort Booking Calendar',
    calendar_month: 'Month',
    calendar_year: 'Year',
    calendar_this_month: 'bookings this month',
    calendar_selected_date: 'Selected Date',
    calendar_loading: 'Loading bookings...',
    calendar_empty_title: 'No bookings',
    calendar_empty_desc: 'This date is still empty.',
    calendar_more: '+{count} more',
    calendar_filter_label: 'Filter calendar month and year',
    package_desc: 'Select the service/package to view or use for booking.',
    package_service_count: '{count} services',

    // Form UI Details
    btn_view: 'View',
    btn_list: 'View List',
    btn_check_availability: 'Check Availability',
    btn_submit: 'Submit Booking',
    btn_update_booking: 'Update Booking',
    btn_saving: 'Saving...',
    form_submitted_desc: 'Bookings submitted for admin review.',
    form_submitted_title: 'Submitted Bookings',
    form_loading_bookings: 'Loading bookings...',
    form_no_bookings: 'No bookings found.',
    form_intake_title: 'Booking Intake Form',
    form_selected_package_empty: 'Select a package for the guest',
    form_selected_package_desc: 'Lead guest, companion, optional children, and package selection',
    form_adults: 'Adults',
    form_children: 'Children',
    form_sec_reservation: 'Reservation Data',
    form_sec_lead_compact: 'Lead Guest Data (Reservation Contact)',
    form_sec_companion_compact: 'Guest 2 Data (Partner / Companion)',
    form_sec_children_compact: 'Children Data',
    form_sec_consent_notes: 'Consent & Additional Notes',
    form_required: 'Required',
    form_optional: 'Optional',
    form_label_full_name: 'Full Name',
    form_label_phone_short: 'WhatsApp / Phone',
    form_label_occupation_company: 'Occupation / Company',
    form_label_companion_job: 'Occupation',
    form_label_lead_package: 'Lead Guest Package',
    form_label_companion_package: 'Guest 2 Package',
    form_sec_extra_adult: 'Guest {number} Data',
    form_label_extra_adult_package: 'Guest {number} Package',
    form_label_child_package: 'Child Package #{number}',
    form_child_added: '{count} Children Added',
    form_no_children: 'No Children',
    form_add_child: 'Add Child',
    form_add_child_data: '+ Add Child Data',
    form_no_child_data: 'No child data',
    form_no_child_desc: 'If the guests are a couple or are not bringing children, skip this section. If they bring children, click the button below.',
    form_child_tag: 'Child #{number}',
    form_remove_child_title: 'Remove this child',
    form_remove_child: 'Remove',
    form_label_child_name: 'Child Name',
    form_label_child_age_years: 'Age (Years)',
    form_label_school_grade: 'Grade / School',
    form_label_astronomy_interest: 'Astronomy Interest',
    form_label_dietary: 'Allergies / Dietary Restrictions',
    form_label_child_notes: 'Child Special Notes',
    form_label_photo_consent: 'Photo Consent',
    form_label_weather_reschedule: 'Weather Reschedule',
    form_label_seating_setup: 'Seating / Setup',
    form_label_slot_status: 'Slot Status',
    form_label_occasion_compact: 'Occasion / Special Moment',
    form_label_extra_details: 'Additional Details',
    form_label_internal_notes: 'Internal Notes',
    form_package_required_note: 'Select at least one package in guest data before submitting the booking.',
    form_placeholder_room: 'Example: 205 / Villa 3',
    form_placeholder_lead_name: 'Lead guest name...',
    form_placeholder_optional: 'Optional',
    form_placeholder_companion_name: 'Partner / companion name...',
    form_placeholder_extra_adult_name: 'Additional guest name...',
    form_placeholder_same_as_lead: 'Optional if same as lead guest',
    form_placeholder_child_name: 'Child full name...',
    form_placeholder_child_age: 'Example: 8',
    form_placeholder_grade: 'Example: Grade 3',
    form_placeholder_child_dietary: 'Food/drink allergies or none',
    form_placeholder_child_notes: 'Afraid of the dark, gets bored easily, needs a companion, etc.',
    form_placeholder_occasion: 'Honeymoon, anniversary, birthday, family trip, etc.',
    form_placeholder_extra: 'Special requests from guest...',
    form_placeholder_internal_notes: 'Notes for admin/internal operations...',
    form_option_male: 'Male',
    form_option_female: 'Female',
    form_option_beginner: 'Beginner',
    form_option_curious: 'Very Curious',
    form_option_advanced: 'Advanced for age',
    form_validation_date: 'Select a date first.',
    form_validation_package: 'Select at least one observation package for the guest.',
    form_validation_lead: 'Complete lead guest name and WhatsApp first.',
    form_validation_child: 'Complete name and age for Child #{number}.',
    form_availability_ok: 'This slot is available and the booking will be logged immediately for operations.',
    form_load_booking_error: 'Failed to load bookings.',
    form_submit_error: 'Failed to create booking.',
    form_submit_success_created: 'Booking {code} created successfully and logged immediately for operations.',
    form_submit_success_updated: 'Booking {code} updated successfully in the operations system.',
    notes_code: 'Code',
    notes_guest: 'Guest',
    notes_empty: 'No additional notes attached.',
    common_first: 'First',
    common_previous: 'Previous',
    common_today: 'Today',
    common_next: 'Next',
    common_last: 'Last',
    common_date: 'Date',
    common_status: 'Status',
    common_event: 'Event',
    common_pax: 'Pax',
    common_booking: 'Booking',
    common_guest: 'Guest',
    common_package: 'Package',
    common_signed: 'Signed',
    common_commission: 'Commission',
    common_action: 'Action',
    common_loading: 'Loading...',
    common_yes: 'Yes',
    common_no: 'No',
    common_room: 'Room',
    common_processing: 'Processing...',
    common_showing: 'Showing {start}-{end} of {total}',
    booking_code: 'Booking Code',
    booking_no_results: 'No bookings found',
    booking_by: 'By {name}',
    dashboard_commission_total: 'Total Commissions Earned',
    dashboard_status_label: 'Status',
    dashboard_invoice_label: 'Invoice',
    dashboard_signed_label: 'Signed',
    dashboard_feedback_label: 'Feedback',
    dashboard_load_commission_error: 'Failed to load commission summary.',
    dashboard_load_reward_error: 'Failed to load reward summary.',
    calendar_previous: 'Previous',
    calendar_today: 'Today',
    calendar_next: 'Next',
    package_title: 'Packages',
    package_form_booking: 'Booking Form',
    package_service_title: 'Package Services',
    package_including: 'Including',
    package_upon_request: 'Upon request',
    payout_title: 'Request Payout',
    payout_history: 'Payout History',
    payout_total_commission: 'Total Commissions Earned',
    payout_total_commission_note: 'Completed, signed, chargeable bookings',
    payout_monthly_reward: 'Monthly Star Reward',
    payout_processing: 'Processing / Completed',
    payout_processing_note: 'Requested, processed, and completed',
    payout_available: 'Available to Withdraw',
    payout_monthly_unit: '{count} units this month',
    payout_star_progress: 'Monthly star progress',
    payout_next_star: 'Progress toward the next star',
    payout_amount: 'Amount USD',
    payout_bank: 'Bank',
    payout_account_holder: 'Account Holder Name',
    payout_account_number: 'Account Number / Note',
    payout_notes: 'Notes',
    payout_sending: 'Sending...',
    payout_request_count: '{count} requests',
    payout_admin_notes: 'Admin Notes',
    payout_empty: 'No payout requests yet.',
    payout_load_error: 'Failed to load payouts.',
    payout_request_error: 'Failed to submit payout request.',
    payout_request_success: 'Payout request sent to admin.',
    payout_status_requested: 'Requested',
    payout_status_processed: 'Processed',
    payout_status_completed: 'Completed',
    payout_status_rejected: 'Rejected',
    instruments_title: 'Instruments',
    instruments_desc: 'Available telescopes in the observatory network.',
    reports_title: 'Reports',
    reports_desc: 'Your booking and observation activity reports.',
    reports_unavailable: 'Feature Not Available Yet',
    reports_unavailable_desc: 'Reports for external staff are still under development.',
    users_title: 'Users',
    users_desc: 'User management for external staff.',
    users_unavailable: 'Feature Not Available Yet',
    users_unavailable_desc: 'User management for external staff is still under development.',
    reschedule_date: 'New date (YYYY-MM-DD)',
    reschedule_start: 'New start time (HH:MM)',
    reschedule_end: 'New end time (HH:MM)',
    reschedule_reason: 'Schedule change reason',
    reschedule_default_reason: 'Guest request',
    reschedule_failed: 'Failed to reschedule booking.',
    reschedule_success: 'Booking rescheduled successfully.',
    booking_complete: 'Complete Booking',
    booking_cancel_guest: 'Cancel by Guest',
    booking_cancel_weather: 'Cancel due to Weather',
    booking_reschedule: 'Reschedule',
    booking_guest: 'Guest',
    booking_package: 'Package',
    booking_schedule: 'Schedule',
    form_payment_room: 'Room charge',
    form_payment_cash: 'Cash',
    form_payment_card: 'Card',
    form_payment_resort: 'Resort billing',
    form_photo_ask: 'Ask guest first',
    form_photo_allowed: 'Allowed',
    form_photo_not_allowed: 'Not allowed',
    form_slot_available: 'Available',
    form_slot_check: 'Needs check',
    form_slot_confirmed: 'Confirmed',
    form_placeholder_nationality: 'Nationality (e.g. Indonesia, Japan)',
    form_placeholder_seating: 'Couple, family nearby, private setup...',
    settings_resort_unset: 'Resort not assigned',
    settings_interface_note: 'Only application interface text changes. User-entered data remains untouched.',
    settings_default_language: 'Default (ID)',
    settings_international_language: 'International (EN)',
    api_error_invalid_booking: 'Invalid booking data.',
    api_error_invalid_payout: 'Invalid payout data.',
    api_error_staff_resort: 'The staff resort profile has not been configured.',
    api_error_payout_balance: 'The amount exceeds the available payout balance.',
    api_error_package_resort: 'The package was not found for this resort.',
    api_error_package_missing: 'Package not found.',
    api_error_staff_missing: 'Staff not found.',
    api_error_booking_missing: 'Booking not found.',
    api_error_invalid_booking_id: 'Invalid booking ID.',
    api_error_invalid_reschedule: 'Invalid reschedule data.',
    accessibility_toggle_menu: 'Toggle menu',
    accessibility_toggle_sidebar: 'Toggle sidebar',
    accessibility_close_menu: 'Close menu',
    accessibility_toggle_language: 'Toggle language',
    experience_sun_observation_tagline: 'Complimentary daytime solar viewing session.',
    experience_beach_stargazing_tagline: 'Evening lounge stargazing on Palm Beach.',
    experience_private_beach_stargazing_tagline: 'Intimate private session on Palm Beach.',
    experience_celestial_dining_tagline: 'Fine dining beneath the stars on Palm Beach.',
    experience_kids_stargazing_tagline: 'Fun and educational stargazing experience for kids in a safe and friendly environment.',
    experience_moon_observation_tagline: 'Guided lunar observation relayed from {location}.',
    experience_night_sky_tagline: 'Wide-field night sky tour relayed from {location}.',
    experience_deep_sky_tagline: 'Deep-sky object viewing relayed from {location}.',
    dashboard_completed_count: '{count} completed bookings',
    dashboard_monthly_reward_amount: '{amount} reward this month',
    payout_star_breakdown: '{stars} full stars + {amount} progress',
  },
};

const API_ERROR_KEYS = {
  'Data booking tidak valid': 'api_error_invalid_booking',
  'Data payout tidak valid': 'api_error_invalid_payout',
  'Staff resort profile is not configured': 'api_error_staff_resort',
  'Amount exceeds available payout balance': 'api_error_payout_balance',
  'Package not found for this resort': 'api_error_package_resort',
  'Package not found': 'api_error_package_missing',
  'Staff not found': 'api_error_staff_missing',
  'Booking not found': 'api_error_booking_missing',
  'Invalid booking id': 'api_error_invalid_booking_id',
  'Invalid reschedule data': 'api_error_invalid_reschedule',
};

const LanguageContext = createContext({
  language: 'id',
  setLanguage: () => {},
  toggleLanguage: () => {},
  t: (key, fallback) => fallback || key,
  localizeApiError: (message, fallback) => message || fallback || '',
});

const STORAGE_KEY = 'ephemeris_staff_language';

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    if (typeof window !== 'undefined') {
      try {
        const saved = localStorage.getItem(STORAGE_KEY);
        if (saved === 'en' || saved === 'id') return saved;
      } catch {
        // ignore
      }
    }
    return 'id';
  });

  const setLanguage = useCallback((newLang) => {
    const lang = newLang === 'en' ? 'en' : 'id';
    setLanguageState(lang);
    try {
      localStorage.setItem(STORAGE_KEY, lang);
      if (typeof document !== 'undefined') {
        document.documentElement.lang = lang;
      }
    } catch {
      // ignore
    }
  }, []);

  const toggleLanguage = useCallback(() => {
    setLanguage(language === 'id' ? 'en' : 'id');
  }, [language, setLanguage]);

  const t = useCallback(
    (key, fallback = '') => {
      const dict = translations[language] || translations.id;
      if (dict && dict[key] !== undefined) {
        return dict[key];
      }
      const fallbackDict = translations.id;
      if (fallbackDict && fallbackDict[key] !== undefined) {
        return fallbackDict[key];
      }
      return fallback || key;
    },
    [language]
  );

  const localizeApiError = useCallback((message, fallback = '') => {
    const normalized = String(message || '').trim().replace(/[.]$/, '');
    const key = API_ERROR_KEYS[normalized];
    return key ? t(key) : (message || fallback);
  }, [t]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t, localizeApiError }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
