'use client';

import { createContext, useContext, useEffect, useState, useCallback } from 'react';

export const translations = {
  id: {
    // Navigation & Sidebar
    nav_dashboard: 'Dasbor',
    nav_booking_form: 'Form Booking',
    nav_package: 'Paket Observasi',
    nav_payout: 'Pencairan Komisi',
    nav_calendar: 'Kalender Jadwal',
    nav_settings: 'Pengaturan',
    nav_main_section: 'Navigasi Utama',
    nav_active_locations: 'Lokasi Aktif',
    nav_logout: 'Keluar Akun',

    // Role Labels
    role_internal: 'Staff Internal',
    role_external: 'Staff External',
    role_astronomer: 'Astronom In-House',
    resort_profile: 'Profil Resort',

    // Header & Clock
    clock_wib: 'WIB',
    clock_utc: 'UTC',
    clock_date: 'Tanggal',
    btn_new_booking: '+ Booking Baru',

    // Settings Page
    settings_title: 'Pengaturan',
    settings_subtitle: 'Kelola preferensi akun, bahasa antarmuka, dan notifikasi Anda.',
    settings_profile_title: 'Profil Pengguna',
    settings_name: 'Nama Lengkap',
    settings_institution: 'Institusi / Peran',
    settings_language_title: 'Bahasa Aplikasi (Language)',
    settings_language_desc: 'Pilih bahasa tampilan antarmuka aplikasi staf (Indonesia atau English).',
    settings_lang_id: 'Bahasa Indonesia (ID)',
    settings_lang_en: 'English (EN)',
    settings_notif_title: 'Notifikasi',
    settings_notif_email_label: 'Notifikasi Email',
    settings_notif_email_desc: 'Terima pemberitahuan status booking melalui email.',
    settings_saved_toast: 'Pengaturan bahasa berhasil diubah!',

    // Common Actions & Tags
    btn_save: 'Simpan',
    btn_cancel: 'Batal',
    btn_close: 'Tutup',
    btn_edit: 'Edit Booking',
    btn_delete: 'Hapus',
    btn_copy_notes: '📄 Salin Seluruh Catatan',
    btn_copied_success: '✓ Berhasil Disalin!',
    btn_open_notes: '🔍 Buka Catatan Lengkap (Popup)',
    btn_submit_booking: 'Submit Booking Observasi',
    btn_add_child: '+ Tambah Data Anak',
    btn_remove: 'Hapus',

    // Status Badges
    status_pending_review: 'Menunggu Admin',
    status_accepted: 'Diterima',
    status_rejected: 'Ditolak',
    status_booked: 'Booked',
    status_finished: 'Selesai',
    status_cancelled: 'Dibatalkan',
    tag_signed: '✓ Signed',
    tag_not_signed: '⏱ Not Signed',

    // Booking View Modal
    view_title: 'Detail Reservasi Staf Operasional',
    view_stat_date: 'Tanggal Observasi',
    view_stat_time: 'Jam & Sesi',
    view_stat_room: 'Nomor Kamar / Villa',
    view_stat_nationality: 'Kebangsaan / Bahasa',
    view_stat_whatsapp: 'WhatsApp Tamu',
    view_stat_pax: 'Jumlah Tamu',
    view_stat_payment: 'Metode Pembayaran',
    view_stat_commission: 'Estimasi Komisi Staf',
    view_stat_star_reward: 'Reward Bintang',
    view_package_banner_title: 'Package Observasi Terpilih',
    view_guest_lead_title: 'Tamu Utama (Lead Guest)',
    view_guest_companion_title: 'Tamu 2 (Pasangan/Pendamping)',
    view_guest_child_title: 'Data Anak',
    view_guest_no_child: 'Tidak membawa anak (Couple / Dewasa saja)',
    view_package_label: 'Package',
    view_notes_banner_title: 'Rincian Catatan Lengkap & Log Form',
    view_notes_banner_desc: 'Klik tombol di kanan untuk membuka popup tampilan teks catatan lengkap di depan layar.',
    view_notes_popup_title: 'Catatan Lengkap & Log Intake Form',
    view_staff_notes_title: 'Catatan Khusus Operasional Lapangan',

    // Booking Form Sections & Fields
    form_title: 'Formulir Reservasi Observasi Tamu',
    form_desc: 'Isi data reservasi tamu untuk pengalaman pengamatan benda langit.',
    form_sec_guest_lead: '1. Data Tamu Utama (Kontak Reservasi)',
    form_sec_guest_companion: '2. Data Tamu 2 (Pasangan/Pendamping)',
    form_sec_children: '3. Data Anak (Opsional / Fleksibel)',
    form_sec_preferences: '4. Preferensi Pengalaman & Observasi',
    form_sec_notes: '5. Catatan Tambahan',
    form_label_name: 'Nama Lengkap Tamu',
    form_label_phone: 'Nomor WhatsApp',
    form_label_email: 'Email (Opsional)',
    form_label_room: 'Nomor Kamar / Villa',
    form_label_nationality: 'Kewarganegaraan',
    form_label_language: 'Bahasa Pilihan Tamu',
    form_label_adult_count: 'Jumlah Dewasa (Adults)',
    form_label_child_count: 'Jumlah Anak (Children)',
    form_label_date: 'Tanggal Observasi',
    form_label_time: 'Waktu / Jam Sesi',
    form_label_package: 'Pilih Package Utama',
    form_label_job: 'Pekerjaan (Opsional)',
    form_label_child_age: 'Umur Anak (Tahun)',
    form_label_child_gender: 'Jenis Kelamin',
    form_label_child_grade: 'Kelas / Jenjang Sekolah',
    form_label_child_interest: 'Tingkat Minat Astronomi',
    form_label_child_allergy: 'Alergi / Pantangan Makanan',
    form_label_child_comfort: 'Catatan Kenyamanan Anak',
    form_label_occasion: 'Momen / Acara Khusus',
    form_label_seating: 'Pengaturan Tempat Duduk',
    form_label_photo: 'Permintaan Foto Teleskop',
    form_label_privacy: 'Preferensi Privasi',
    form_label_reschedule: 'Persetujuan Cuaca / Reschedule',
    form_label_payment: 'Metode Pembayaran',
    form_placeholder_search: 'Cari tamu, paket, kamar...',
    form_pax_adult_only: 'Hanya Tamu Dewasa / Couple',
    form_pax_with_children: 'Tamu Membawa Anak',
    form_empty_children_prompt: 'Saat ini belum ada data anak ditambahkan (Cocok untuk Couple / Dewasa).',
    form_empty_children_btn: '+ Tambah Data Anak',
    form_alert_saved: 'Booking berhasil disimpan!',
    form_alert_error: 'Gagal menyimpan booking.',

    // Dashboard
    dashboard_internal_title: 'Dashboard Staff Internal',
    dashboard_external_title: 'Dashboard Observer Eksternal',
    dashboard_welcome: 'Selamat datang, {name}. Kelola booking customer resort di sini.',
    dashboard_total_bookings: 'Total Booking Saya',
    dashboard_active_bookings: 'Booking Aktif',
    dashboard_upcoming: 'Akan Datang',
    dashboard_finished: 'Selesai',
    dashboard_all_time: 'Sepanjang waktu',
    dashboard_operational_note: 'Langsung masuk operasional',
    dashboard_active_schedule: 'Jadwal booking aktif',
    dashboard_finished_note: 'Observasi selesai',
    dashboard_star_progress: 'Progress Bintang Staff',
    dashboard_points: '{points} / 50 poin',
    dashboard_star_rule: '10 booking = 1 bintang, package kids: 20 anak = 1 bintang',
    dashboard_history_title: 'Riwayat Booking (5 Teratas)',
    dashboard_see_all: 'Lihat Semua',
    dashboard_no_history: 'Tidak ada riwayat booking.',
    dashboard_booking_guide: 'Panduan Booking',
    dashboard_guide_new: 'Booking baru yang dibuat akan masuk dengan status Pending Review dan memerlukan persetujuan (ACC) dari admin sebelum menjadi aktif.',
    dashboard_guide_status: 'Pantau status booking Anda di tabel riwayat. Pending Review berarti menunggu ACC admin.',
    dashboard_guide_invoice: 'Pembayaran tetap dicatat manual oleh resort.',
    dashboard_guide_signed: 'Centang setelah tamu tanda tangan fisik.',
    dashboard_guide_feedback: 'Kirim link WhatsApp setelah experience selesai.',
    table_station: 'Stasiun',
    table_date: 'Tanggal',
    table_time: 'Waktu',

    // Calendar & Packages
    calendar_title: 'Kalender Booking Bulanan',
    calendar_all_staff: 'Kalender Semua Staff',
    calendar_resort: 'Kalender Booking Resort',
    calendar_month: 'Bulan',
    calendar_year: 'Tahun',
    calendar_this_month: 'booking bulan ini',
    calendar_selected_date: 'Tanggal Dipilih',
    calendar_loading: 'Memuat booking...',
    calendar_empty_title: 'Tidak ada booking',
    calendar_empty_desc: 'Tanggal ini masih kosong.',
    calendar_more: '+{count} lainnya',
    calendar_filter_label: 'Filter bulan dan tahun kalender',
    package_desc: 'Pilih service/package yang ingin dilihat atau digunakan untuk booking.',
    package_service_count: '{count} service',

    // Form UI Details
    btn_view: 'Lihat',
    btn_list: 'Lihat List',
    btn_check_availability: 'Cek Ketersediaan',
    btn_submit: 'Submit Booking',
    btn_update_booking: 'Update Booking',
    btn_saving: 'Menyimpan...',
    form_submitted_desc: 'Booking yang sudah dikirim ke admin untuk direview.',
    form_submitted_title: 'Daftar Booking',
    form_loading_bookings: 'Memuat booking...',
    form_no_bookings: 'Belum ada booking.',
    form_intake_title: 'Booking Intake Form',
    form_selected_package_empty: 'Pilih package untuk tamu',
    form_selected_package_desc: 'Data tamu utama, pasangan/pendamping, anak (opsional), dan pilihan package',
    form_adults: 'Dewasa',
    form_children: 'Anak',
    form_sec_reservation: 'Data Reservasi',
    form_sec_lead_compact: 'Data Tamu Utama (Kontak Reservasi)',
    form_sec_companion_compact: 'Data Tamu 2 (Pasangan / Pendamping)',
    form_sec_children_compact: 'Data Anak',
    form_sec_consent_notes: 'Consent & Catatan Tambahan',
    form_required: 'Wajib Diisi',
    form_optional: 'Opsional',
    form_label_full_name: 'Nama Lengkap',
    form_label_phone_short: 'WhatsApp / Telepon',
    form_label_occupation_company: 'Pekerjaan / Instansi',
    form_label_companion_job: 'Pekerjaan',
    form_label_lead_package: 'Package Tamu Utama',
    form_label_companion_package: 'Package Tamu 2',
    form_sec_extra_adult: 'Data Tamu {number}',
    form_label_extra_adult_package: 'Package Tamu {number}',
    form_label_child_package: 'Package Anak #{number}',
    form_child_added: '{count} Anak Ditambahkan',
    form_no_children: 'Tidak Membawa Anak',
    form_add_child: 'Tambah Anak',
    form_add_child_data: '+ Tambah Data Anak',
    form_no_child_data: 'Tidak ada data anak',
    form_no_child_desc: 'Jika tamu adalah pasangan (couple) atau tidak membawa anak, lewati bagian ini. Jika membawa anak, klik tombol di bawah.',
    form_child_tag: 'Anak #{number}',
    form_remove_child_title: 'Hapus anak ini',
    form_remove_child: 'Hapus',
    form_label_child_name: 'Nama Anak',
    form_label_child_age_years: 'Umur (Tahun)',
    form_label_school_grade: 'Kelas / Sekolah',
    form_label_astronomy_interest: 'Minat Astronomi',
    form_label_dietary: 'Alergi / Pantangan',
    form_label_child_notes: 'Catatan Khusus Anak',
    form_label_photo_consent: 'Photo Consent',
    form_label_weather_reschedule: 'Weather Reschedule',
    form_label_seating_setup: 'Seating / Setup',
    form_label_slot_status: 'Slot Status',
    form_label_occasion_compact: 'Occasion / Momen Khusus',
    form_label_extra_details: 'Detail Tambahan',
    form_label_internal_notes: 'Internal Notes',
    form_package_required_note: 'Pilih minimal satu package pada data tamu sebelum submit booking.',
    form_placeholder_room: 'Contoh: 205 / Villa 3',
    form_placeholder_lead_name: 'Nama tamu utama...',
    form_placeholder_optional: 'Opsional',
    form_placeholder_companion_name: 'Nama pasangan / pendamping...',
    form_placeholder_extra_adult_name: 'Nama tamu tambahan...',
    form_placeholder_same_as_lead: 'Opsional jika sama dengan tamu utama',
    form_placeholder_child_name: 'Nama lengkap anak...',
    form_placeholder_child_age: 'Contoh: 8',
    form_placeholder_grade: 'Contoh: Grade 3',
    form_placeholder_child_dietary: 'Alergi makanan/minuman atau none',
    form_placeholder_child_notes: 'Takut gelap, mudah bosan, perlu pendamping khusus, dll.',
    form_placeholder_occasion: 'Honeymoon, anniversary, birthday, family trip, dll.',
    form_placeholder_extra: 'Request khusus dari tamu...',
    form_placeholder_internal_notes: 'Catatan untuk admin/operasional internal...',
    form_option_male: 'Laki-laki (Male)',
    form_option_female: 'Perempuan (Female)',
    form_option_beginner: 'Pemula (Beginner)',
    form_option_curious: 'Sangat Tertarik (Curious)',
    form_option_advanced: 'Mahir untuk usianya',
    form_validation_date: 'Pilih tanggal terlebih dahulu.',
    form_validation_package: 'Pilih minimal satu package observasi untuk tamu.',
    form_validation_lead: 'Lengkapi Nama dan WhatsApp Tamu Utama terlebih dahulu.',
    form_validation_child: 'Lengkapi Nama dan Umur untuk Anak #{number}.',
    form_availability_ok: 'Slot ini biasanya tersedia. Konfirmasi final tetap oleh admin.',
    form_load_booking_error: 'Gagal memuat booking.',
    form_submit_error: 'Booking gagal dibuat.',
    form_submit_success_created: 'Booking {code} berhasil dibuat dan menunggu persetujuan admin.',
    form_submit_success_updated: 'Booking {code} berhasil diperbarui dan menunggu persetujuan admin.',
    notes_code: 'Kode',
    notes_guest: 'Tamu',
    notes_empty: 'Tidak ada catatan tambahan yang terlampir.',
  },
  en: {
    // Navigation & Sidebar
    nav_dashboard: 'Dashboard',
    nav_booking_form: 'Booking Form',
    nav_package: 'Observation Packages',
    nav_payout: 'Commission Payout',
    nav_calendar: 'Schedule Calendar',
    nav_settings: 'Settings',
    nav_main_section: 'Main Navigation',
    nav_active_locations: 'Active Locations',
    nav_logout: 'Sign Out',

    // Role Labels
    role_internal: 'Internal Staff',
    role_external: 'External Staff',
    role_astronomer: 'In-House Astronomer',
    resort_profile: 'Resort Profile',

    // Header & Clock
    clock_wib: 'WIB',
    clock_utc: 'UTC',
    clock_date: 'Date',
    btn_new_booking: '+ New Booking',

    // Settings Page
    settings_title: 'Settings',
    settings_subtitle: 'Manage your profile, interface language, and notification preferences.',
    settings_profile_title: 'User Profile',
    settings_name: 'Full Name',
    settings_institution: 'Institution / Role',
    settings_language_title: 'Application Language',
    settings_language_desc: 'Select the interface language for the staff portal (Indonesian or English).',
    settings_lang_id: 'Bahasa Indonesia (ID)',
    settings_lang_en: 'English (EN)',
    settings_notif_title: 'Notifications',
    settings_notif_email_label: 'Email Notifications',
    settings_notif_email_desc: 'Receive booking status updates and review alerts via email.',
    settings_saved_toast: 'Language setting updated successfully!',

    // Common Actions & Tags
    btn_save: 'Save',
    btn_cancel: 'Cancel',
    btn_close: 'Close',
    btn_edit: 'Edit Booking',
    btn_delete: 'Delete',
    btn_copy_notes: '📄 Copy Entire Notes',
    btn_copied_success: '✓ Copied Successfully!',
    btn_open_notes: '🔍 Open Full Notes (Popup)',
    btn_submit_booking: 'Submit Observation Booking',
    btn_add_child: '+ Add Child Data',
    btn_remove: 'Remove',

    // Status Badges
    status_pending_review: 'Pending Review',
    status_accepted: 'Accepted',
    status_rejected: 'Rejected',
    status_booked: 'Booked',
    status_finished: 'Finished',
    status_cancelled: 'Cancelled',
    tag_signed: '✓ Signed',
    tag_not_signed: '⏱ Not Signed',

    // Booking View Modal
    view_title: 'Operational Staff Reservation Detail',
    view_stat_date: 'Observation Date',
    view_stat_time: 'Time & Session',
    view_stat_room: 'Room / Villa Number',
    view_stat_nationality: 'Nationality / Language',
    view_stat_whatsapp: 'Guest WhatsApp',
    view_stat_pax: 'Guest Count',
    view_stat_payment: 'Payment Method',
    view_stat_commission: 'Est. Staff Commission',
    view_stat_star_reward: 'Star Reward',
    view_package_banner_title: 'Selected Observation Package',
    view_guest_lead_title: 'Lead Guest (Contact)',
    view_guest_companion_title: 'Guest 2 (Partner/Companion)',
    view_guest_child_title: 'Child Data',
    view_guest_no_child: 'No children (Couple / Adults only)',
    view_package_label: 'Package',
    view_notes_banner_title: 'Full Form Notes & Intake Log',
    view_notes_banner_desc: 'Click the button on the right to open the full raw notes popup on screen.',
    view_notes_popup_title: 'Full Form Notes & Intake Log',
    view_staff_notes_title: 'Field Operational Notes',

    // Booking Form Sections & Fields
    form_title: 'Guest Observation Booking Form',
    form_desc: 'Fill in guest reservation details for stargazing experience.',
    form_sec_guest_lead: '1. Lead Guest Data (Reservation Contact)',
    form_sec_guest_companion: '2. Guest 2 Data (Partner/Companion)',
    form_sec_children: '3. Children Data (Optional / Dynamic)',
    form_sec_preferences: '4. Observation Experience Preferences',
    form_sec_notes: '5. Additional Notes',
    form_label_name: 'Guest Full Name',
    form_label_phone: 'WhatsApp Number',
    form_label_email: 'Email (Optional)',
    form_label_room: 'Room / Villa Number',
    form_label_nationality: 'Nationality',
    form_label_language: 'Guest Preferred Language',
    form_label_adult_count: 'Adults Count',
    form_label_child_count: 'Children Count',
    form_label_date: 'Observation Date',
    form_label_time: 'Session Time',
    form_label_package: 'Select Main Package',
    form_label_job: 'Occupation (Optional)',
    form_label_child_age: 'Child Age (Years)',
    form_label_child_gender: 'Gender',
    form_label_child_grade: 'School Grade',
    form_label_child_interest: 'Astronomy Interest Level',
    form_label_child_allergy: 'Allergies / Dietary Restrictions',
    form_label_child_comfort: 'Child Comfort Notes',
    form_label_occasion: 'Special Occasion',
    form_label_seating: 'Seating Arrangement',
    form_label_photo: 'Telescope Photo Request',
    form_label_privacy: 'Privacy Preference',
    form_label_reschedule: 'Weather / Reschedule Consent',
    form_label_payment: 'Payment Method',
    form_placeholder_search: 'Search guest, package, room...',
    form_pax_adult_only: 'Adults Only / Couple',
    form_pax_with_children: 'Guests with Children',
    form_empty_children_prompt: 'No children added currently (Ideal for Couple / Adults).',
    form_empty_children_btn: '+ Add Child Data',
    form_alert_saved: 'Booking successfully saved!',
    form_alert_error: 'Failed to save booking.',

    // Dashboard
    dashboard_internal_title: 'Internal Staff Dashboard',
    dashboard_external_title: 'External Observer Dashboard',
    dashboard_welcome: 'Welcome, {name}. Manage resort customer bookings here.',
    dashboard_total_bookings: 'My Total Bookings',
    dashboard_active_bookings: 'Active Bookings',
    dashboard_upcoming: 'Upcoming',
    dashboard_finished: 'Completed',
    dashboard_all_time: 'All time',
    dashboard_operational_note: 'Sent directly to operations',
    dashboard_active_schedule: 'Active booking schedule',
    dashboard_finished_note: 'Completed observations',
    dashboard_star_progress: 'Staff Star Progress',
    dashboard_points: '{points} / 50 points',
    dashboard_star_rule: '10 bookings = 1 star, kids package: 20 children = 1 star',
    dashboard_history_title: 'Booking History (Top 5)',
    dashboard_see_all: 'See All',
    dashboard_no_history: 'No booking history.',
    dashboard_booking_guide: 'Booking Guide',
    dashboard_guide_new: 'New bookings are submitted as Pending Review and require admin approval before becoming active.',
    dashboard_guide_status: 'Track booking status in the history table. Pending Review means waiting for admin approval.',
    dashboard_guide_invoice: 'Payments are still recorded manually by the resort.',
    dashboard_guide_signed: 'Check signed after the guest signs the physical form.',
    dashboard_guide_feedback: 'Send the WhatsApp feedback link after the experience is completed.',
    table_station: 'Station',
    table_date: 'Date',
    table_time: 'Time',

    // Calendar & Packages
    calendar_title: 'Monthly Booking Calendar',
    calendar_all_staff: 'All Staff Calendar',
    calendar_resort: 'Resort Booking Calendar',
    calendar_month: 'Month',
    calendar_year: 'Year',
    calendar_this_month: 'bookings this month',
    calendar_selected_date: 'Selected Date',
    calendar_loading: 'Loading bookings...',
    calendar_empty_title: 'No bookings',
    calendar_empty_desc: 'This date is still empty.',
    calendar_more: '+{count} more',
    calendar_filter_label: 'Filter calendar month and year',
    package_desc: 'Select the service/package to view or use for booking.',
    package_service_count: '{count} services',

    // Form UI Details
    btn_view: 'View',
    btn_list: 'View List',
    btn_check_availability: 'Check Availability',
    btn_submit: 'Submit Booking',
    btn_update_booking: 'Update Booking',
    btn_saving: 'Saving...',
    form_submitted_desc: 'Bookings submitted for admin review.',
    form_submitted_title: 'Submitted Bookings',
    form_loading_bookings: 'Loading bookings...',
    form_no_bookings: 'No bookings found.',
    form_intake_title: 'Booking Intake Form',
    form_selected_package_empty: 'Select a package for the guest',
    form_selected_package_desc: 'Lead guest, companion, optional children, and package selection',
    form_adults: 'Adults',
    form_children: 'Children',
    form_sec_reservation: 'Reservation Data',
    form_sec_lead_compact: 'Lead Guest Data (Reservation Contact)',
    form_sec_companion_compact: 'Guest 2 Data (Partner / Companion)',
    form_sec_children_compact: 'Children Data',
    form_sec_consent_notes: 'Consent & Additional Notes',
    form_required: 'Required',
    form_optional: 'Optional',
    form_label_full_name: 'Full Name',
    form_label_phone_short: 'WhatsApp / Phone',
    form_label_occupation_company: 'Occupation / Company',
    form_label_companion_job: 'Occupation',
    form_label_lead_package: 'Lead Guest Package',
    form_label_companion_package: 'Guest 2 Package',
    form_sec_extra_adult: 'Guest {number} Data',
    form_label_extra_adult_package: 'Guest {number} Package',
    form_label_child_package: 'Child Package #{number}',
    form_child_added: '{count} Children Added',
    form_no_children: 'No Children',
    form_add_child: 'Add Child',
    form_add_child_data: '+ Add Child Data',
    form_no_child_data: 'No child data',
    form_no_child_desc: 'If the guests are a couple or are not bringing children, skip this section. If they bring children, click the button below.',
    form_child_tag: 'Child #{number}',
    form_remove_child_title: 'Remove this child',
    form_remove_child: 'Remove',
    form_label_child_name: 'Child Name',
    form_label_child_age_years: 'Age (Years)',
    form_label_school_grade: 'Grade / School',
    form_label_astronomy_interest: 'Astronomy Interest',
    form_label_dietary: 'Allergies / Dietary Restrictions',
    form_label_child_notes: 'Child Special Notes',
    form_label_photo_consent: 'Photo Consent',
    form_label_weather_reschedule: 'Weather Reschedule',
    form_label_seating_setup: 'Seating / Setup',
    form_label_slot_status: 'Slot Status',
    form_label_occasion_compact: 'Occasion / Special Moment',
    form_label_extra_details: 'Additional Details',
    form_label_internal_notes: 'Internal Notes',
    form_package_required_note: 'Select at least one package in guest data before submitting the booking.',
    form_placeholder_room: 'Example: 205 / Villa 3',
    form_placeholder_lead_name: 'Lead guest name...',
    form_placeholder_optional: 'Optional',
    form_placeholder_companion_name: 'Partner / companion name...',
    form_placeholder_extra_adult_name: 'Additional guest name...',
    form_placeholder_same_as_lead: 'Optional if same as lead guest',
    form_placeholder_child_name: 'Child full name...',
    form_placeholder_child_age: 'Example: 8',
    form_placeholder_grade: 'Example: Grade 3',
    form_placeholder_child_dietary: 'Food/drink allergies or none',
    form_placeholder_child_notes: 'Afraid of the dark, gets bored easily, needs a companion, etc.',
    form_placeholder_occasion: 'Honeymoon, anniversary, birthday, family trip, etc.',
    form_placeholder_extra: 'Special requests from guest...',
    form_placeholder_internal_notes: 'Notes for admin/internal operations...',
    form_option_male: 'Male',
    form_option_female: 'Female',
    form_option_beginner: 'Beginner',
    form_option_curious: 'Very Curious',
    form_option_advanced: 'Advanced for age',
    form_validation_date: 'Select a date first.',
    form_validation_package: 'Select at least one observation package for the guest.',
    form_validation_lead: 'Complete lead guest name and WhatsApp first.',
    form_validation_child: 'Complete name and age for Child #{number}.',
    form_availability_ok: 'This slot is usually available. Final confirmation is still handled by admin.',
    form_load_booking_error: 'Failed to load bookings.',
    form_submit_error: 'Failed to create booking.',
    form_submit_success_created: 'Booking {code} created successfully and is waiting for admin approval.',
    form_submit_success_updated: 'Booking {code} updated successfully and is waiting for admin approval.',
    notes_code: 'Code',
    notes_guest: 'Guest',
    notes_empty: 'No additional notes attached.',
  },
};

const LanguageContext = createContext({
  language: 'id',
  setLanguage: () => {},
  toggleLanguage: () => {},
  t: (key, fallback) => fallback || key,
});

const STORAGE_KEY = 'ephemeris_staff_language';

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    if (typeof window !== 'undefined') {
      try {
        const saved = localStorage.getItem(STORAGE_KEY);
        if (saved === 'en' || saved === 'id') return saved;
      } catch {
        // ignore
      }
    }
    return 'id';
  });

  const setLanguage = useCallback((newLang) => {
    const lang = newLang === 'en' ? 'en' : 'id';
    setLanguageState(lang);
    try {
      localStorage.setItem(STORAGE_KEY, lang);
      if (typeof document !== 'undefined') {
        document.documentElement.lang = lang;
      }
    } catch {
      // ignore
    }
  }, []);

  const toggleLanguage = useCallback(() => {
    setLanguage(language === 'id' ? 'en' : 'id');
  }, [language, setLanguage]);

  const t = useCallback(
    (key, fallback = '') => {
      const dict = translations[language] || translations.id;
      if (dict && dict[key] !== undefined) {
        return dict[key];
      }
      const fallbackDict = translations.id;
      if (fallbackDict && fallbackDict[key] !== undefined) {
        return fallbackDict[key];
      }
      return fallback || key;
    },
    [language]
  );

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
